
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: echo "Building..."

      - name: Deploy to Test
        run: echo "Deploying to Test..."

  deploy-prod:
    needs: build-and-deploy-test
    runs-on: ubuntu-latest
    environment:
      name: production
      # This requires manual approval in the GitHub UI
      # You can also use wait_timer if you want a delay instead
      deployment_branch_policy:
        protected_branches: true
    steps:
      - name: Deploy to Prod
        run: echo "Deploying to Prod..."
