
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: echo "Building..."

      - name: Deploy to Test
        run: echo "Deploying to Test..."

  deploy-prod:
    needs: build-and-deploy-test
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Deploy to Prod
        run: echo "Deploying to Prod..."
